### ISSUE TITLE
Fix spacing on listing items in People Listing view

### ISSUE THREAD

**Issue by cewing** [isawnyu/isaw.theme#36] opened 2015-06-06 02:31 UTC
The details of each person's listing in a list of people are a bit wonky.  They do not match the comps.  Please fix.

**Comment by kevintbrooks** [comment] 2015-06-08 15:50
CSS has been updated. Can you be sure the Faculty Position data lives in p.facultyPosition (looks like the <p> is closed early).

**Comment by skleinfeldt** [comment] 2015-06-08 21:53
Reassigning to @alecpm who is doing the bug fixing this week.

**Comment by paregorios** [comment] 2015-06-09 17:56
I'm not clear on what in particular the problem is here. @kevintbrooks can you advise so I can decide whether this is a "must fix" before deployment?

**Comment by kevintbrooks** [comment] 2015-06-09 18:32
This looks like a pretty simple fix in the template - the facultyPosition classed tag isn't actually holding the data it's meant to. For example: 

`<p class="facultyPosition"></p><p>Assistant Professor of Western Asian Archaeology and History</p>`

**Comment by paregorios** [comment] 2015-06-09 18:53
moving this to pre-deploy milestone

**Comment by alecpm** [comment] 2015-07-08 14:25
This should be fixed on staging.

**Closed as completed** 2015-08-06 14:34 UTC
Labels: question
