### ISSUE TITLE
News listing tile problem

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/isaw.theme#17] opened 2015-06-03 17:28 UTC
Some news items (aka blog) have no description and some have long descriptions, which messes up the tile arrangement. Please make CSS adjustments to fix this if possible.

**Comment by kevintbrooks** [comment] 2015-06-04 19:41
Can you send along a screen shot. Jagged as it is, the grid itself looks to be in working order.

**Comment by cewing** [comment] 2015-06-04 20:17
@kevintbrooks I'm pretty sure the issue is actually the issue you've identified in #30 

If my work there fixes the problem, we can close this.

**Comment by kevintbrooks** [comment] 2015-06-08 16:07
Looks good!

**Closed as completed by kevintbrooks** 2015-06-08 16:07 UTC
Labels: layout issue
