### ISSUE TITLE
error on pages requiring authentication

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.theme#66] opened 2015-07-30 20:13 UTC
Users who attempt to follow a link to a page that requires authentication, if they are not logged in, should be directed to a page that informs them that the content they are trying to reach requires login (and present a login button). Instead, they see the following error:
<img width="1253" alt="screen shot 2015-07-30 at 10 59 04 am" src="https://cloud.githubusercontent.com/assets/7882896/8993882/d8ad2c82-36d5-11e5-8afd-0098521742c2.png">

**Comment by alecpm** [comment] 2015-08-04 04:19
This should be fixed now on isaw4-dev, but I think I'm seeing the same issue on production.  The login_form from the WebserverAuth addon expects the login url to contain "login_form" but on these permission redirects it uses "require_login" instead.

**Comment by paregorios** [comment] 2015-08-04 15:11
The same issue does indeed occur on production, where we’d been ignoring it since we assumed it would get fixed as part of the upgrade. But somehow it slipped through the cracks. 

Is this a fix in code (i.e., it will always be fixed wherever buildout:master gets deployed and run, or do we need to intervene on production so that associated database changes get made?

We can live with it on production for a few more days. But I’d prefer not to have to remember to clean it up after upgrade. Automagically goes away is my preferred experience.

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by k2soule** [comment] 2015-08-04 15:15
Thanks, Alex!
Can you remove the redundancy? The "Please log in here" message is just fine, but it currently appears twice.

**Comment by alecpm** [comment] 2015-08-04 15:23
It's fixed in the repo, so it should apply automatically on production once we've upgraded.  It's essentially due to a minor incompatibility between Products.WebServerAuth and the latest Plone.

**Comment by alecpm** [comment] 2015-08-04 16:12
The duplicate link was yet another, minor, WebserverAuth incompatibility with the Plone 4.3 theme.  Should be fixed now.

**Comment by k2soule** [comment] 2015-08-04 16:17
Thanks!

**Comment by paregorios** [comment] 2015-08-05 15:20
This seems to have regressed on staging. Try /about/employee/admin-procedures

**Comment by alecpm** [comment] 2015-08-05 15:25
I think this will be resolved once @cguardia clears out the custom templates from skins and portal_template_customizations.

**Comment by paregorios** [comment] 2015-08-06 14:27
Apparently @cguardia has not yet taken this step on staging in the course of working on #74. 

Test: /members/paregorian/foo

I will hold this ticket, marked "reviewing" until #74 is complete, then revisit.

**Comment by alecpm** [comment] 2015-08-06 16:22
This is fixed once again.  @cguardia had removed the template customizations, but for some reason (which I'm looking into) the skin ordering fixes in the theme profile were not applied during the upgrade/migration.

**Comment by paregorios** [comment] 2015-08-07 12:37
seems to be working well now on staging. Can we close this ticket given preceding comment from @alecpm ?

**Comment by k2soule** [comment] 2015-08-07 15:55
I'm getting "This page isn't redirecting properly" on dev.

**Comment by paregorios** [comment] 2015-08-07 15:56
Huh. My test this morning worked. What URL are you trying to resolve?

**Comment by k2soule** [comment] 2015-08-07 16:00
/about/employee/admin-procedures (on the Win7 machine). I'll go check my Mac browsers, to see if the behavior is different.

**Comment by paregorios** [comment] 2015-08-07 16:07
I can't reproduce that error. I happily see:

![login](https://cloud.githubusercontent.com/assets/263285/9140129/722ed080-3cf4-11e5-95f5-97e14327f4b2.jpg)

**Comment by k2soule** [comment] 2015-08-07 16:07
Hmm. Login redirect is working on my mac. I'll go kick the pc...

**Closed as completed** 2015-08-07 17:24 UTC
Labels: bug, reviewing, most urgent
